### ISSUE TITLE
Alterar logos das aplicações

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/programa#1072]
Alterar logos de todos os aplicativos de acordo com essa [issue](https://github.com/practice-uffs/programa/issues/969):

- [x] practice-uffs/mural#432
- [ ] [Practice Bem-Estar](https://github.com/practice-uffs/app-saude/issues/57)
- [x] [Practice Forms](https://github.com/practice-uffs/forms/issues/6)
- [x] [Practice Maker](https://github.com/practice-uffs/maker/issues/58)
---
- [x] [Ajustar logos no website do Practice](https://github.com/practice-uffs/website-programa/issues/109)

**Comment by PracticeUFFSBot** [comment]
Criei as pastas dessa issue no Google Drive:
* <img width="16" height="16" src="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png" /> [Pasta da issue](https://drive.google.com/drive/folders/130nU3ilkb64uykIJNrALgP53n_e1nksg) 
* 🔽 [Entrada](https://drive.google.com/drive/folders/1LhUsLe62oxLmzEHiDJA9f_BWEwnLXYmR)
* 🔼 [Saída](https://drive.google.com/drive/folders/1VjKs8TpArLNNhsdxEvrvn5j16ER3VJEQ)

**Comment by CleissonVieira** [comment]
Os ícones estão fora de padrão. Segue referência abaixo:

Tamanho X+2:
- Aplicativo da Aura (sem link)

Tamanho X+1:
- [UFFS Virtual](https://drive.google.com/drive/folders/13OQ3qlC0smzQVUp5lD_An_Wcg5yyGxVB)

Tamanho X:
- [APP Bem estar](https://drive.google.com/drive/folders/1nW2YXuP1gMqr_qeEQGNalZyuOWUFssZU)
- [Forms](https://drive.google.com/drive/folders/1YEwKj4_BRf7S_jMzsMVq3OCOVZaZFi9e)
- [Maker](https://drive.google.com/drive/folders/1DKIvIN4LHKdpAzh1pHsqbHFKNOl6jOx6)

Tamanho X-1:
- [Mural](https://drive.google.com/drive/folders/1hGKBrAAI6jMsl_i2l7oH4xi4s8MZPhAE)

Tamanho X-2:
- [APP Boas vindas](https://drive.google.com/drive/folders/1tQwwFmC4RpO6QB7wzpugPjw7ZaRlrNs0)
