### ISSUE TITLE
Postagens Junho 2023

### ISSUE THREAD

**Issue by ghost** [practice-uffs/programa#1512]
Issue designada para a organização do conteúdo (cards e reels) do mês de Junho

- [x] [Conteúdo de postagens de Junho 2023](https://github.com/practice-uffs/programa/issues/1510)
- [x] [Reels de Junho](https://github.com/practice-uffs/programa/issues/1515)
- [ ] [Stories de Junho de 2023](https://github.com/practice-uffs/programa/issues/1511)

**Comment by ghost** [comment]
os conteúdos que não foram ainda postados foram remanejados para outras issues
