### ISSUE TITLE
Criação das descrições para os vídeos a serem postados no YouTube

### ISSUE THREAD

**Issue by morgana-mo** [practice-uffs/programa#469]
Essa issue tem como objetivo a criação das descrições para os vídeos a serem postados no YouTube do PRACTICE para darmos o prosseguimento a atividade iniciada na issue #434 . Os as descrições a serem criadas são para os seguintes vídeos únicos:
- [x] #295 
- [x] #296 
- [x] #297 
- [x] #244 
- [x] #341 
E para as seguintes séries de vídeos:
- [x] Tutorial ShotCut, episódios de 1 a 6 (#131 , #132 , #133 , #134 , #337 , #338 );
- [x] Tutorial OBS Studio, episódios de 1 a 5 (#317 , #318 , #319 , #320 , #321);
- [x] Tutorial de edição de imagem, episódios de 1 a 6 (#288 , #289 , #290 , #291 , #292 , #293 ).
Como a @luizatonial já criou as [descrições](https://docs.google.com/document/d/1eK_xsqbf5SdwVuDHm2X8U0OHrxRWdiYY1xrcFmtlbwU/edit) para a série Tutorial de edição de imagem, estas precisam apenas passar por uma revisão textual.

**Comment by PracticeUFFSBot** [comment]
Criei as pastas dessa issue no Google Drive:
* <img width="16" height="16" src="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png" /> [Pasta da issue](https://drive.google.com/drive/folders/1ejHRWReogHUuNC5FOJyQ5uguvJX7ZRZx) 
* 🔽 [Entrada](https://drive.google.com/drive/folders/1qSFVRIEq_SQTDPj_i_1ylU36RxJHUjqZ)
* 🔼 [Saída](https://drive.google.com/drive/folders/1H937L9ZF3Y01HZ9FLM24P9GEvWCAFA18)

**Comment by morgana-mo** [comment]
@luizdameda preciso de uma ajudinha sua com a [descrição](https://docs.google.com/document/d/1de-I-E4fW2qrXiX1IG0OKjaWFR2kZcxk1o100spRLJ4/edit) do vídeo de Políticas de licença.

**Comment by luizdameda** [comment]
> @luizdameda preciso de uma ajudinha sua com a [descrição](https://docs.google.com/document/d/1de-I-E4fW2qrXiX1IG0OKjaWFR2kZcxk1o100spRLJ4/edit) do vídeo de Políticas de licença.

Oi!! Dei uma olhada agora, a meu ver a descrição está bem boa, explica bem a finalidade do vídeo e o assunto que será abordado. Vi que está faltando as referências das imagens que utilizei e da música, além disso, tem mais alguma coisa que posso ajudar?

Logo adiciono no doc as referências dos materiais utilizados.

**Comment by morgana-mo** [comment]
Boa tarde gente!
Vou precisar de uma ajudinha dos editores dos vídeos!

- @amandasegattob eu preciso que você insira as [informações](https://docs.google.com/document/d/1oydoYFqThOPT-mOtyOZT0hrtWIGfST7j6p1UvgnbFJQ/edit?usp=sharing) que faltam sobre o vídeo da issue #244 ;
- @luizdameda eu preciso que você insira as [informações](https://docs.google.com/document/d/1sGiB2MguXZx1G4NUCZn1ByyPDpZMmLRIsuNiIXr8LM8/edit) que faltam sobre o vídeo da issue #296 ;

- @robisonjose quando você retornar do afastamento peço que você insira as informações que faltam nas descrições do vídeo de [edição de podcast](https://docs.google.com/document/d/1Wds6_0cXwU-f9I4tFGrLIkf8SSj3cnJNIjwuKsjIEmk/edit) e no de [Dicas para produzir um bom texto](https://docs.google.com/document/d/1N8pCbvVkxHaR8biQapvHt3hjarRywvCPnqnp41XupSw/edit).

Fiquem a vontade para fazer alterações nos textos!

**Comment by morgana-mo** [comment]
@mariagelain pode designar alguém da @practice-uffs/con-conteudo  para trabalhar nessa issue com as correções?

De momento pronto para a revisão textual temos esse arquivo [aqui](https://docs.google.com/document/d/1de-I-E4fW2qrXiX1IG0OKjaWFR2kZcxk1o100spRLJ4/edit) que é a descrição de um vídeo que vai ser postado essa semana.

**Comment by thaliafriedrich** [comment]
> @mariagelain pode designar alguém da @practice-uffs/con-conteudo para trabalhar nessa issue com as correções?
> 
> De momento pronto para a revisão textual temos esse arquivo [aqui](https://docs.google.com/document/d/1de-I-E4fW2qrXiX1IG0OKjaWFR2kZcxk1o100spRLJ4/edit) que é a descrição de um vídeo que vai ser postado essa semana.

@mariagelain, @morgana-mo, posso trabalhar nessas revisões.

**Comment by thaliafriedrich** [comment]
Fiz a revisão da descrição do vídeo sobre as políticas de licença. As demais descrições que estão na pasta de entrada dessa issue também já estão prontas para a revisão textual?

**Comment by morgana-mo** [comment]
> Fiz a revisão da descrição do vídeo sobre as políticas de licença. As demais descrições que estão na pasta de entrada dessa issue também já estão prontas para a revisão textual?

Eu estou aguardando confirmação do pessoal do mídia sobre alguma informações, mas  [aqui](https://docs.google.com/document/d/1MYYuRQhrjRKojNM896AzeD3QmFG-HayJ/edit?usp=drive_web&ouid=107124994030999807400&rtpof=true) há as descrições da série de vídeos sobre edição de imagem que já podem passar por revisão textual.

**Comment by luizdameda** [comment]
Finalizei agora o vídeo com dicas para videoaulas, issue #296, e fiz a complementação dos campos vazios no doc de descrição do vídeo.

Já pode ser liberado para postagem no YouTube.

**Comment by morgana-mo** [comment]
> Finalizei agora o vídeo com dicas para videoaulas, issue #296, e fiz a complementação dos campos vazios no doc de descrição do vídeo.
> 
> Já pode ser liberado para postagem no YouTube.

Obrigada @luizdameda !

**Comment by morgana-mo** [comment]
@amandasegattob  e @luizatonial  criei um [rascunho inicial](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit) das descriões da série OBS, gostaria que vocês dessem uma olhada,pois usei como base o roteiro e como nunca utilizei o OBS não tenho muita noção do que se passa nos vídeos.

**Comment by morgana-mo** [comment]
@vini2reis  criei um [rascunho inicial](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) das descriçõe da série Tutorial ShotCut, gostaria que você desse uma olhada , utilizei como base os roteiros e suas informações. Fico no aguardo dos feedbacks :D

**Comment by thaliafriedrich** [comment]
> @mariagelain pode designar alguém da @practice-uffs/con-conteudo para trabalhar nessa issue com as correções?
> 
> De momento pronto para a revisão textual temos esse arquivo [aqui](https://docs.google.com/document/d/1de-I-E4fW2qrXiX1IG0OKjaWFR2kZcxk1o100spRLJ4/edit) que é a descrição de um vídeo que vai ser postado essa semana.

As revisões das descrições da série de edição de imagens e do vídeo com dicas para videoaulas estão finalizadas.

**Comment by thaliafriedrich** [comment]
> > Fiz a revisão da descrição do vídeo sobre as políticas de licença. As demais descrições que estão na pasta de entrada dessa issue também já estão prontas para a revisão textual?
> 
> Eu estou aguardando confirmação do pessoal do mídia sobre alguma informações, mas [aqui](https://docs.google.com/document/d/1MYYuRQhrjRKojNM896AzeD3QmFG-HayJ/edit?usp=drive_web&ouid=107124994030999807400&rtpof=true) há as descrições da série de vídeos sobre edição de imagem que já podem passar por revisão textual.

As revisões das descrições da série de edição de imagens e do vídeo com dicas para videoaulas estão finalizadas.

**Comment by luizatonial** [comment]
> @amandasegattob e @luizatonial criei um [rascunho inicial](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit) das descriões da série OBS, gostaria que vocês dessem uma olhada, pois usei como base o roteiro e como nunca utilizei o OBS não tenho muita noção do que se passa nos vídeos. Fico no aguardo dos feedbacks :D

A princípio achei que as descrições estão bem completas @morgana-mo. 
Eu estou realizando a gravação dos vídeos ainda devido a alguns probleminhas que ocorreram durante as mesmas. 
Caso haja alguma alteração eu comunico posteriormente.

**Comment by vini2reis** [comment]
> @vini2reis criei um [rascunho inicial](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) das descriçõe da série Tutorial ShotCut, gostaria que você desse uma olhada , utilizei como base os roteiros e suas informações. Fico no aguardo dos feedbacks :D

**Comment by vini2reis** [comment]
> @vini2reis criei um [rascunho inicial](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) das descriçõe da série Tutorial ShotCut, gostaria que você desse uma olhada , utilizei como base os roteiros e suas informações. Fico no aguardo dos feedbacks :D

@morgana-mo Boa Tarde

- Na descrição do episódio 4 nesse trecho: "Demonstramos como você pode adicionar “Textos: Simples” ou  “Textos: 3D” e maneiras de como configurá-lo e temporalizá-lo." acho melhor colocar apenas "Demonstramos como você pode adicionar Textos e maneiras de como configurá-los e temporalizá-los."

- Na parte dos créditos dos vídeos pode colocar Gravação e Edição com o meu nome também em todos e adiciona Narração com o nome do Rafael

Acho que isso, nas outras partes considero que estejam boas as descrições

**Comment by morgana-mo** [comment]
> > @vini2reis criei um [rascunho inicial](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) das descriçõe da série Tutorial ShotCut, gostaria que você desse uma olhada , utilizei como base os roteiros e suas informações. Fico no aguardo dos feedbacks :D
> 
> @morgana-mo Boa Tarde
> 
> - Na descrição do episódio 4 nesse trecho: "Demonstramos como você pode adicionar “Textos: Simples” ou  “Textos: 3D” e maneiras de como configurá-lo e temporalizá-lo." acho melhor colocar apenas "Demonstramos como você pode adicionar Textos e maneiras de como configurá-los e temporalizá-los."
> 
> - Na parte dos créditos dos vídeos pode colocar Gravação e Edição com o meu nome também em todos e adiciona Narração com o nome do Rafael
> 
> Acho que isso, nas outras partes considero que estejam boas as descrições

Obrigada pelo feedback @vini2reis farei as alterações e colocarei o texto para revisão textual :D

**Comment by morgana-mo** [comment]
Boa tarde !
@thaliafriedrich  as descrições das séries [Tutorial ShotCut](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) e [ Tutorial OBS Studio ](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit) já podem passar pela revisão textual.

**Comment by morgana-mo** [comment]
> > Boa tarde !
> > @thaliafriedrich as descrições das séries [Tutorial ShotCut](https://docs.google.com/document/d/16kOKF6FjtP7kp7h-5jbxiBpC1vnOzb3pqgKBXCSftfg/edit) e [ Tutorial OBS Studio ](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit) já podem passar pela revisão textual.
> 
> Boa tarde. As revisões foram feitas. Fiz algumas alterações para melhorar as questões textuais e deixei um comentário no arquivo para verificar.

Verificado e corrigido @thaliafriedrich

**Comment by morgana-mo** [comment]
@thaliafriedrich os demais vídeos da pasta [vídeos únicos](https://drive.google.com/drive/folders/1rMd4Nz0Vk8S_0OIl1LXXhmNP9bE2xFmD) já podem passar por revisão textual

**Comment by thaliafriedrich** [comment]
> @thaliafriedrich os demais vídeos da pasta [vídeos únicos](https://drive.google.com/drive/folders/1rMd4Nz0Vk8S_0OIl1LXXhmNP9bE2xFmD) já podem passar por revisão textual

Revisões feitas!

**Comment by morgana-mo** [comment]
@practice-uffs/con-midia as descrições foram devidamente escritas e revisadas,aguardamos ainda o @robisonjose aprovar as que se referem aos vídeos editados por ele. 
Aos demais agradeço a colaboração e lembro que quando possível devem ser colocados os créditos faltantes nos seus referidos arquivos!
Uma ótima semana a todos!

**Comment by robisonjose** [comment]
Descrições revisadas e aprovadas! Peço desculpas pela demora.

**Comment by morgana-mo** [comment]
Descrições completas, aguardamos agora as finalizações dos vídeos em andamento  para o complemento dos créditos!

**Comment by morgana-mo** [comment]
@amandasegattob  assim que possível [colocar os dados ](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit) na descrição

**Comment by luizatonial** [comment]
@morgana-mo revisei todas as descrições, parece que está tudo ok, só estamos resolvendo se vamos tirar um link ou não.

A @amandasegattob fez um comentário sobre a maneira de colocar os créditos, como você está postando todos, acho que teria que seguir o mesmo padrão (mas isso é só a minha opinião), se vc puder dar uma olhadinha no comentário.

**Comment by morgana-mo** [comment]
Alguém da @practice-uffs/con-conteudo  para revisar [esse material](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit)

**Comment by isabelirk** [comment]
> 
> 
> Alguém da @practice-uffs/con-conteudo para revisar [esse material](https://docs.google.com/document/d/1HoUoUDoQaexpUKEh8fmFk8vGcQd6Xot517qiP78BjxY/edit)?

eu posso revisar!

**Comment by isabelirk** [comment]
Boa tarde, realizei a revisão. Vou marcar a @Eweline (pois é a revisora oficial agora) para que dê uma última olhada no documento.
Atenciosamente.

**Comment by morgana-mo** [comment]
> Boa tarde, realizei a revisão. Vou marcar a @Eweline (pois é a revisora oficial agora) para que dê uma última olhada no documento.
> Atenciosamente.

Obrigada @isabelirk , aguardo o ok da @Eweline

**Comment by Eweline** [comment]
Boa noite.
Os textos estão bem legais.
Dei algumas contribuições. Estão em comentários no arquivo.
Peço para que a @morgana-mo dê uma olhada para aceitar ou recusar as sugestões. E se alguém da @practice-uffs/con-conteudo também quiser revisar, agradeço.

Outra coisa, preciso colocar meu nome na parte "Revisão Textual" do arquivo? Ainda estou aprendendo como tudo funciona 😬

**Comment by Eweline** [comment]
Modifiquei algumas coisas que comentei e já resolvi. Qualquer coisa, podem pedir que eu mudo novamente.

**Comment by morgana-mo** [comment]
> Modifiquei algumas coisas que comentei e já resolvi. Qualquer coisa, podem pedir que eu mudo novamente.

Gostei muito da revisão que você fez!
Amanhã já vou dar início as postagens

**Comment by morgana-mo** [comment]
Finalmente terminamos as postagens!
Obrigada a TODOS pela colaboração!
