### ISSUE TITLE
Pacote de artes enlatadas para DCS

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/programa#667]
O Eliton Paulo Novais (eliton.novais@uffs.edu.br), da Diretoria de Comunicação Social da UFFS, entrou em contato para fazermos uma parceria. A ideia é o practice produzir um conjunto de elementos de arte "elatados" (coisa pré-feitas que eles poderão editar no futuro).

A lista do que precisa ser feito é o seguinte:

Assim, fizemos uma lista com as principais artes que precisamos que sejam elaboradas:

- [x] Uma imagem genérica para cada curso de graduação e pós-graduação (#740)
- [x] Processo seletivo para professor(es) substituto(s) (#739)
- [x] Processo seletivo para ingresso de alugo regular de mestrados (#738)
- [x] Processo seletivo para ingresso em disciplinas isoladas de mestrados (#737)
- [ ] Atualização do NSO (#736)
- [x] Curso de Extensão: inscrições abertas (#735)
- [x] Concurso Público (#734)
- [x] Nota de falecimento (#733)
- [x] Aula magna (#732)
- [ ] Eleições para Conselho de Campus (#731)
- [ ] Consuni (#730)
- [x] Semanas Acadêmicas (#729)
- [ ] Assuntos Estudantis (#728)
- [x] Aviso (#727)
- [x] Atenção (#726)

Precisamos criar uma issue para cada uma dessas artes. As especificações de cada uma delas pode ser tratada diretamente com o solicitante por e-mail (não temos trafegar tudo pelo mural para melhorar o fluxo nesse caso).

A @practice-uffs/ger-auxilio pode criar uma issue de trabalho para item da lista acima e ajudar/coordenar o processo junto ao cliente e à @practice-uffs/con-design . Não há prazo definido, então podemos espalhar essas tarefas ao longo das próximas sprints.

**Comment by PracticeUFFSBot** [comment]
Criei as pastas dessa issue no Google Drive:
* <img width="16" height="16" src="https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_32dp.png" /> [Pasta da issue](https://drive.google.com/drive/folders/1jt0PZ9jq5wmzIMEMMR-CJdmBGsdYDIxC) 
* 🔽 [Entrada](https://drive.google.com/drive/folders/15I89K7aJi81i7atKcAlH_G70RLl8lN49)
* 🔼 [Saída](https://drive.google.com/drive/folders/1VINhgm6CIBI3gXwkAJmCh8SYlsCx23dd)

**Comment by TaynaraCh** [comment]
Após reunião realizada na segunda-feira, Claudineia, Morgana e eu, decidimos que a @anacarolinamorigi irá ficar responsável pela demanda, devendo organizar a mesma e também criar as artes. Fico a disposição para auxilia-la.

**Comment by anacarolinamorigi** [comment]
Boa noite!

Como combinado com a @TaynaraCh, para modelos iniciais antes do briefing da parceria, aqui estão eles:
https://www.canva.com/design/DAEoVnxHyMs/share/preview?token=bBhtIMqdUS2Olxzh_hQpRA&role=EDITOR&utm_content=DAEoVnxHyMs&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

Esses estão disponíveis como bases e poderão ser utilizadas futuramente. Vale colocar alguns pontos sobre as artes:
* Modelo 1 e 2 - foi desenvolvido para serem modelos para os pacotes de avisos, atenção até a atualização do NSO, com exceção do pacote de nota de falecimento;
* Modelo 3 - desenvolvido para o pacote de notas de falecimento;
* Modelo 4 - desenvolvido para o pacote de cursos de graduação e pós-graduação, sendo esse desenvolvido a partir das cores dos cursos e o logotipo desses;
* Modelo 5 e 6 - desenvolvido para o pacote dos processos seletivos.

Espero que gostem! <3

**Comment by TaynaraCh** [comment]
Ok, vamos lá. 
Primeiramente, acredito que as artes devam seguir uma linguagem, pertencer a uma unidade, rever isso! Uma série de elementos, paleta de cores e tipografia irá trazer uma identidade visual aos cards. 
Outro ponto, são no mínimo 15 cards, no link constam apenas 6.
O logotipo da UFFS NÃO pode ser alterado como no modelo 6. 
Foi pedido para que usássemos imagens genéricas para cards de cursos e pós graduação, tem que ser refeito.
Modelos de processos seletivos não tem espaço para escrever as informações, deve ser revisado também.

Acredito que com a saída da @anacarolinamorigi amanhã, ela não conseguirá concluir o trabalho, sendo assim, iremos discutir em reunião da equipe sobre quem ficará responsável pela conclusão.

**Comment by TaynaraCh** [comment]
Refiz e criei mais modelos de cards de divulgação, utilizei as mesmas diretrizes que encaminhei para a Ana, paleta de cores em tons de verde e a cor branca e fonte Fira Sans. Também atualizei as issues correspondente a cada arte iniciada. 
Os arquivos ficaram agrupados da seguinte forma:

**[Pacote](https://www.canva.com/design/DAEolxkM8TM/share/preview?token=ibdGoCHmVg-fhil2RKCSIg&role=EDITOR&utm_content=DAEolxkM8TM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) de imagens genéricas para cada curso de graduação e pós graduação** . Para exemplificar a ideia que tive, criei apenas três modelos, após aprovação ou pedido de alterações, irei finalizar o restante;

**[Pacote](https://www.canva.com/design/DAEonY9_RRM/share/preview?token=hZsfYv94HX3zlxaUduRllA&role=EDITOR&utm_content=DAEonY9_RRM&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) avisos.** No link estão cards em que a intenção é transmitir avisos e informações, sendo eles:
- Curso de Extensão: inscrições abertas;
- Concurso Público;
- Nota de falecimento;
- Aula magna;
- Semanas Acadêmicas;
-  Aviso;
- Atenção.


 **[Pacote](https://www.canva.com/design/DAEonEWsaOs/share/preview?token=oVh-JckWZZiuyUaissZDtA&role=EDITOR&utm_content=DAEonEWsaOs&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) processos seletivos**. No link estão diferentes cards para postagem os processos seletivos:
-  Processo seletivo para professor(es) substituto(s);
-  Processo seletivo para ingresso de alugo regular de mestrados;
-   Processo seletivo para ingresso em disciplinas isoladas de mestrados.

Quanto aos cards citados a seguir, só será possível a elaboração depois que houver maior detalhamento do que deve conter em cada arte. 
- Atualização do NSO;
- Eleições para Conselho de Campus;
- Consuni;
- Assuntos Estudantis.

Sendo assim, acredito que possamos enviar um e-mail para o solicitante com o link do que já foi elaborado, para que o mesmo peça por ajustes e também nos forneça o conteúdo das solicitações ainda não iniciadas. Caso seja necessário, podemos marcar uma reunião para melhor abordarmos assunto. @morgana-mo, pode me auxiliar com o envio do e-mail?

**Comment by morgana-mo** [comment]
@TaynaraCh auxilio sim!

**Comment by morgana-mo** [comment]
Email enviado ao solicitante!

**Comment by TaynaraCh** [comment]
Como não obtivemos retorno sobre o material enviado a issue será fechada, reabriremos caso necessário.
