### ISSUE TITLE
Postar Cartilhas em redes sociais

### ISSUE THREAD

**Issue by VIF-Franca** [practice-uffs/programa#74]
Após o fechamento das issues de cada cartilha postar nas redes sociais com o link para o site.

- [x] Cartilha Lives e videoconferências #28;
- [x] Cartilha iluminação, áudio e ângulo #45;
- [ ]  Cartilha ferramenta edição de vídeo #11;
- [x] Cartilha edição de imagem #13;

- [x] #60 

- [x] #61 

- [x] @practice-uffs/con-design e @practice-uffs/con-material  teremos alguma arte especial para postar ? ou apenas a conversão da capa da cartilha para o tamanho adequado para cada rede social ?

**Comment by elisribas** [comment]
@estelavilasboas 

Revisa as orientações de cartilhas criadas pela Maria, considerando ajustes gráficos necessários para que tenhamos um modelo padrão - de excelência - que poderá ser replicado para todas as futuras produções. Ver #46  

Após, revisa todas as cartilhas indicadas acima. Depois da revisão, me dá um OK para podermos fechar as issues e divulgar os materiais no site.

**Comment by estelavilasboas** [comment]
> Após o fechamento das issues de cada cartilha postar nas redes sociais com o link para o site.
> 
> * [ ]  Cartilha Lives e videoconferências #28;
> * [ ]  Cartilha iluminação, áudio e ângulo #45;
> * [ ]   Cartilha ferramenta edição de vídeo #11;
> * [ ]  Cartilha edição de imagem #13.
> * [ ]  @practice-uffs/con-design e @practice-uffs/con-material  teremos alguma arte especial para postar ? ou apenas a conversão da capa da cartilha para o tamanho adequado para cada rede social ?

Respondendo ao último item, creio que as imagens criadas na Issue [# 39](https://github.com/practice-uffs/programa/issues/39) possam ser utilizadas como base para divulgação dessas cartilhas. A não ser que encontrem necessidade em criar imagens exclusivas para sua divulgação.

(Revisões das cartilhas em andamento)

**Comment by VIF-Franca** [comment]
![image](https://user-images.githubusercontent.com/66980370/92349594-fdb8a880-f0ac-11ea-95fb-d290d6a9c7d7.png)

![image](https://user-images.githubusercontent.com/66980370/92349638-1d4fd100-f0ad-11ea-8de6-71f549648c20.png)

**Comment by VIF-Franca** [comment]
DÚVIDA

A) sobre qual link colocar, iremos direcionar o leitor para acessar o arquivo no drive ou no site ? caso seja o site já existe os link ?

**Comment by Dovyski** [comment]
@practice-uffs/con-design por favor, criar a arte relacionada com essa postagem. Colocar na pasta da issue no drive. Quando estiverem prontas, o @VIF-Franca fará a postagem.

@VIF-Franca qualquer link de material finalizado do PRACTICE precisa ser relacionado ao site do programa. Links para o Google Drive são internos e de trabalho (no máximo para interação com os clientes). Utilize os links dos materiais que estão listados aqui https://practice.uffs.cc/recursos/

**Comment by alessandrapedrotti** [comment]
Lista atualizada de cartilhas liberadas para a postagem:

- [ ] #13;
- [ ] #45;
- [ ] #60;
- [ ] #61;
As cartilhas #11 e #28 não estão concluídas ainda.

@practice-uffs/con-design trabalhar com as cartilhas que foram liberadas pela equipe de conteúdo.

**Comment by estelavilasboas** [comment]
Fiz mais simples considerando que haverá uma descrição junto das imagens.
![image](https://user-images.githubusercontent.com/30927758/92654250-f4eeef00-f2c5-11ea-8db1-640f027d42cf.png)
O que acham?

**Comment by estelavilasboas** [comment]
As imagens estão na [pasta](https://drive.google.com/drive/folders/15GqPpZMsuuWfZKIynw7csvnVsxyr40iu).
Considerei que seriam postadas separadamente no Instagram, portanto os nomes dos arquivos estão como ordem de postagem (1234). Caso optem por postar em um carrossel no Instagram, a ordem será invertida (4321).
Como no momento são apenas 4 cartilhas, podem ser agrupadas em um único post para Twitter e Facebook.

**Comment by Dovyski** [comment]
Ao meu ver, o alcance das cartilhas nas redes sociais será maior se fizermos um post por cartilha. Em relação a lives realizadas, como são muitas, acho que podemos agrupar em "Lives do mês XXX" usando carrossel.

**Comment by VIF-Franca** [comment]
> Lista atualizada de cartilhas liberadas para a postagem:
> 
> * [x]  #13;
> * [x]  #45;
> * [x]  #60;
> * [x]  #61;
>   As cartilhas #11 e #28 não estão concluídas ainda.
> 
> @practice-uffs/con-design trabalhar com as cartilhas que foram liberadas pela equipe de conteúdo.

Cartilhas postadas. 


Postagens em aberto: 

- [ ] #11 

- [ ] #28

**Comment by VIF-Franca** [comment]
> As imagens estão na [pasta](https://drive.google.com/drive/folders/15GqPpZMsuuWfZKIynw7csvnVsxyr40iu).
> Considerei que seriam postadas separadamente no Instagram, portanto os nomes dos arquivos estão como ordem de postagem (1234). Caso optem por postar em um carrossel no Instagram, a ordem será invertida (4321).
> Como no momento são apenas 4 cartilhas, podem ser agrupadas em um único post para Twitter e Facebook.

@estelavilasboas tu pode criar para essa cartilha (#28)? ou pode colocar na pasta do drive a versão editável da imagem pq ai consigo editar pelo photopea, acho eu rsrs

**Comment by estelavilasboas** [comment]
A imagem da cartilha #28 já está na pasta. Logo teremos finalizada a #80. 
O manual #11 ainda está em discussão na equipe.
Imagem da catilha 28 foi considerada uma postagem única.

**Comment by VIF-Franca** [comment]
Perfeito, @estelavilasboas a #28 já está postada.
Para as demais postagens das cartilhas #11 e #80  quando finalizadas, podemos abrir uma nova issue para postar!
